QWIN-36915 : Mention users in an article
exo-addons/news pull request #279
Opened 2020-11-25 10:54 UTC by Rdidmohamedelhadi

2020-12-02 12:34 UTC, ahamdi requested changes
Build is failing because we need a UT to cover this fix.

2020-12-03 19:10 UTC, ahamdi requested changes

2020-12-03 19:10 UTC, ahamdi commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +                  + encoder.encodeHTML(identity.getProfile().getFullName()) + "</a>";
Please try to merge all those conditions in one by directly checking the string after the @ character . Note that we can expected any type of HTML entities or any other characters

2020-12-04 11:54 UTC, Rdidmohamedelhadi commented on services/src/main/java/org/exoplatform/news/NewsServiceImpl.java
> +                  + encoder.encodeHTML(identity.getProfile().getFullName()) + "</a>";
done

2020-12-04 17:24 UTC, ahamdi approved these changes
LGTM

2020-12-07 08:37 UTC, merged